
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
    working_dir: /data
    depends_on:
      - db
      - mailhog
    environment:
      MAIL_MAILER: smtp
      MAIL_HOST: mailhog
      MAIL_PORT: 1025
      MAIL_ENCRYPTION: null
      MAIL_FROM_ADDRESS: "no-reply@example.test"
      MAIL_FROM_NAME: "MyCampus"
      QUEUE_CONNECTION: sync
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
  web:
    image: nginx:1.20-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
    depends_on:
      - app
  
  db:
    build: ./infra/mysql
    environment:
      - MYSQL_DATABASE=laravel_mycampus
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=secret
      - TZ=Asia/Tokyo
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: